### ISSUE TITLE
processing files?

### ISSUE THREAD

**Issue by lazee486** [e-m3din4/wigle-wifi#1]
would it be possible to process a csv with this? im using a mikrotik router to log wifi mac and signal strength (can use arduino too) and was thinking google location api, but this looks like it would work as wifi geolocation with wigle...which i like as ive been contributing for years :)

**Comment by e-m3din4** [comment]
you will need to negotiate according your plans for api  commercial use, seems you want to process a considerable amount of api calls and wigle has its own restrictions... i just wrote the code for the script to avoid call api from browser/website.

**Comment by e-m3din4** [comment]
there are other services / databases that will fulfill your goals for sure, Mozilla Location Services is amazing and they use signal strenght to do trilateration, you can check the python script i wrote for it.
